### ISSUE TITLE
Build issue on Angular 6 application

### ISSUE THREAD

**Issue by dblervaque** [rafaelblink/angular-custom-checkbox#1]
Hello @rafaelblink,

I was looking to your library but I am facing an issue at build time.
I am using Angular 6 and I think you have to update your package ;)

Stacktrace : 
`ng build --aot`

`ERROR in angular-custom-checkbox\angular-custom-checkbox.ts(6,2): Error during template compile of 'CustomCheckboxModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/angular-custom-checkbox/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

Will you update your package in a near future ?

Kind regards,

David

**Comment by rafaelblink** [comment]
Hey @dblervaque thank you for your feedback, I'll make the update for the v6.

**Comment by JoaoPortella** [comment]
+1, asap please...
