### ISSUE TITLE
A typescript question

### ISSUE THREAD

**Issue by KKSzymanowski** [rafaelblink/angular-custom-checkbox#2]
Hello,

I've come across your package looking for a reference for creating my custom checkbox component and I saw [this method](https://github.com/rafaelblink/angular-custom-checkbox/blob/master/src/app/custom-checkbox/custom-checkbox.component.ts#L38):
```ts
setDisabledState ? (isDisabled: boolean) : void {}
```
which comes from the `ControlValueAccessor` interface.
I'm not at all proficient in Typescript but if I understand correctly the question mark after the method name in an interface specifies that the method does not have to be implemented in a concrete class using that interface. Your class is a concrete class and you provided the method with a body(empty body but still). I'm having trouble figuring out what this question mark does in this specific scenario and I would much appreciate an explanation.

Thanks in advance.

**Comment by rafaelblink** [comment]
Hey Szy, sorry bro, I didn't understand your question, can you explain better?

**Comment by KKSzymanowski** [comment]
What does the question mark do after the `setDisabledState` method name?
If I recall correctly it worked fine without it.

**Comment by rafaelblink** [comment]
It's true, works fine without it, I think I put that due to previous versions of angular, but present version works fine without it.
I'm developing a version of this library with angular v7 support. I'm definitely going to remove this.
Thank you.
